name: Deploy Fake E-Commerce Backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy backend with PM2
        run: |
          cd /home/mufkimustache/projects/fake-api-eccomerce

          echo "ğŸ”„ Pull latest code"
          git pull origin master

          echo "ğŸ“¦ Install dependencies"
          cd backend
          npm install

          echo "ğŸ— Build backend"
          npm run build

          echo "ğŸš€ Reload PM2"
          pm2 reload fake-ecommerce-api

          pm2 save

          echo "âœ… Deploy finished"
